/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashInventoryRouteImport } from './routes/_dash.inventory'
import { Route as DashOrdersRouteImport } from './routes/_dash.orders'
import { Route as DashShiftHistoryRouteImport } from './routes/_dash.shift-history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashInventoryRoute = DashInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashRoute,
} as any)
const DashOrdersRoute = DashOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashRoute,
} as any)
const DashShiftHistoryRoute = DashShiftHistoryRouteImport.update({
  id: '/shift-history',
  path: '/shift-history',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof DashInventoryRoute
  '/orders': typeof DashOrdersRoute
  '/shift-history': typeof DashShiftHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof DashInventoryRoute
  '/orders': typeof DashOrdersRoute
  '/shift-history': typeof DashShiftHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/_dash/inventory': typeof DashInventoryRoute
  '/_dash/orders': typeof DashOrdersRoute
  '/_dash/shift-history': typeof DashShiftHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventory' | '/orders' | '/shift-history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventory' | '/orders' | '/shift-history'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/_dash/inventory'
    | '/_dash/orders'
    | '/_dash/shift-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/inventory': {
      id: '/_dash/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashInventoryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/orders': {
      id: '/_dash/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashOrdersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/shift-history': {
      id: '/_dash/shift-history'
      path: '/shift-history'
      fullPath: '/shift-history'
      preLoaderRoute: typeof DashShiftHistoryRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashInventoryRoute: typeof DashInventoryRoute
  DashOrdersRoute: typeof DashOrdersRoute
  DashShiftHistoryRoute: typeof DashShiftHistoryRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashInventoryRoute: DashInventoryRoute,
  DashOrdersRoute: DashOrdersRoute,
  DashShiftHistoryRoute: DashShiftHistoryRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
